// //
// // API.AI Unity SDK Sample
// // =================================================
// //
// // Copyright (C) 2015 by Speaktoit, Inc. (https://www.speaktoit.com)
// // https://www.api.ai
// //
// // ***********************************************************************************************************************
// //
// // Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// // the License. You may obtain a copy of the License at
// //
// //     http://www.apache.org/licenses/LICENSE-2.0
// //
// // Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// // an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// // specific language governing permissions and limitations under the License.
// //
// // ***********************************************************************************************************************
//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;

public class Landmark
{

  public string name;
  public string container;


  public Landmark(string landmarkName, string containerName)
  {
    name      = landmarkName;
    container = containerName;
  }

  public string getContainer()
  {
    return container;
  }

  public string getName()
  {
    return name;
  }

}


